rules:
  - id: express-pg-sqli
    message: |-
      Insufficient permissions to view rule definition.
      This rule is only visible to logged in users. Log in to see this rule.
    severity: WARNING
    languages:
      - javascript
      - typescript
